apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  uri: bW9uZ29kYjovL21vbmdvOjI3MDEvc2V1X2JhbmNvX2RlX2RhZG9z # Substitua pelo valor codificado em Base64 do seu URI MongoDB
