apiVersion: v1
kind: Service
metadata:
  name: fast-food-service # Nome do Service
  namespace: default
spec:
  selector:
    app: fast-food # Conecta-se aos pods que têm a label 'app: fast-food'
  ports:
    - protocol: TCP # Usa o protocolo TCP para comunicação
      port: 3000 # Porta externa do Service (acessível de fora do cluster)
      targetPort: 3000 # Porta onde os pods estão ouvindo (dentro do cluster)
      nodePort: 32000 # Porta fixa para acesso externo
  type: NodePort # Exposição externa através de uma porta do nó
